# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64f33a0c73521f54219f6883774470fa"
name = "Grouping"
application_url = "https://groupbuy-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "pubsub://groupbuy-app-635bf:shopify-orders-create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "pubsub://groupbuy-app-635bf:shopify-orders-updated"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "pubsub://groupbuy-app-635bf:shopify-orders-cancelled"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_delivery_customizations,read_locations,read_orders,read_payment_customizations,read_payment_mandate,read_publications,read_shipping,unauthenticated_read_checkouts,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_app_proxy,write_checkouts,write_delivery_customizations,write_order_edits,write_orders,write_payment_customizations,write_payment_mandate,write_products,write_publications,write_shipping,read_validations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://groupbuy-app.fly.dev/auth/callback",
  "https://groupbuy-app.fly.dev/auth/shopify/callback",
  "https://groupbuy-app.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://groupbuy-app.fly.dev/api"
subpath = "gbs"
prefix = "apps"
